# this shows how we can extend/change an existing official image from Docker Hub

FROM php:8.2-cli
# highly recommend you always pin versions for anything beyond dev/learn

WORKDIR /usr/src/myapp
# change working directory to root of nginx webhost
# using WORKDIR is preferred to using 'RUN cd /some/path'

COPY index.php index.php

# I don't have to specify EXPOSE or CMD because they're in my FROM
